### ISSUE TITLE
An intake catalog for ICESat-2 ATLAS data

### ISSUE THREAD

**Issue by weiji14** [icesat2py/icepyx#106]
Just continuing the discussion from the recent [Icepyx meeting](https://discourse.pangeo.io/t/icepyx-team-meetings/722) where there was an interest on [Intake](https://intake.readthedocs.io) catalogs. To make things more concrete on what an 'intake' catalog is, here's a link to an example for ATL06 data I've made, and a short snippet.

https://github.com/weiji14/deepicedrain/blob/17067ad3cb2c8165d2ea5af4dba3fd827da9e6ae/deepicedrain/atlas_catalog.yaml#L46-L105

```yaml
metadata:
  description: 'An intake catalog for loading ICESat-2 ATLAS datasets'
  version: 1
sources:
  icesat2atl06:
    description: 'Reads in ICESat-2 ATL06 data into an xarray.Dataset, one date and one laser pair at a time'
    args:
      chunks:
        delta_time: 50000
      path_as_pattern: ATL06_{datetime:%Y%m%d%H%M%S}_{referencegroundtrack:4}{cyclenumber:2}{orbitalsegment:2}_{version:3}_{revision:2}.h5
      # urlpath: https://n5eil02u.ecs.nsidc.org/opendap/hyrax/ATLAS/ATL06.003/{{date.strftime("%Y.%m.%d")}}/ATL06_*_*{{orbitalsegment}}_003_01.h5
      urlpath: simplecache::https://n5eil01u.ecs.nsidc.org/ATLAS/ATL06.00{{version}}/{{date.strftime("%Y.%m.%d")}}/ATL06_*_{{referencegroundtrack}}*{{orbitalsegment}}_00{{version}}_01.h5
      xarray_kwargs:
        combine: by_coords
        engine: h5netcdf
        group: /{{laser}}/land_ice_segments
        mask_and_scale: true
        parallel: true
      storage_options:
        simplecache:
          cache_storage: ATL06.00{{version}}/{{date.strftime("%Y.%m.%d")}}
          same_names: True
    # https://intake.readthedocs.io/en/latest/catalog.html#parameter-definition
    parameters:
        date:
          description: Year, month, and day of data acquisition
          type: datetime
          default: 2020.03.06
          min: 2018.10.14
          max: 2020.04.04  # note missing 2018.12.09, and gap from 2019.06.27 to 2019.07.25 (inclusive)
        referencegroundtrack:
          description: ICESat-2 Reference Ground Track number
          type: str
          default: ""  # Default: "" (all), min: "0000", max: "1387"
        orbitalsegment:
          description: Orbital Segment
          type: str
          default: 11
          allowed: [10, 11, 12]
        laser:
          description: Name of laser
          type: str
          default: gt2l
          allowed: ["gt1l", "gt1r", "gt2l", "gt2r", "gt3l", "gt3r"]
        version:
          description: Version number
          type: int
          default: 3
          allowed: [1, 2, 3]
    driver: intake_xarray.netcdf.NetCDFSource
```

The code to read/plot data would look like this:

```python
import intake

catalog = intake.open_catalog("atlas_catalog.yaml")
dataset = catalog.icesat2atl06.read()  # load data into xarray
catalog.icesat2atl06.hvplot.quickview()  # interactive hvplot
```

There's a couple of 'features':
- Parsing the datetime, cycle number, reference ground track, orbital segment, etc directly from the filename (see also https://www.anaconda.com/blog/intake-parsing-data-from-filenames-and-paths)
- Data is pulled from NSIDC directly if not available locally (requires netrc authentication) using local caching (see https://intake.readthedocs.io/en/latest/catalog.html#caching-source-files-locally)
- Predefined intreactive plots with hvplot (see https://intake.readthedocs.io/en/latest/gui.html#plot)

Current issues to be ironed out:
- Ideally we would just connect to OPeNDAP so users won't have to 'download' the data before they can view the metadata, but authentication is tricky (see https://github.com/pydap/pydap/issues/188).
- Can only read in one laser at a time, but this can be addressed by extending xarray or writing our own custom ATLxx reader (happy to submit a patch)
- Alternatively, if we can download the ATL06 data and put everything into a flat HDF5 structure, this would work seamlessly

Note that intake is actively being developed at https://github.com/intake/intake, and there's a rich plugin ecosystem at https://intake.readthedocs.io/en/latest/plugin-directory.html to handle just about any filetype. I've been working with an 'out-of-the-box' solution so far, but it would be great to have an ICESat-2 specific intake plugin! Happy to answer and questions or listen to suggestions.
